FORMAT: 1A
HOST: http://spordisemu.apiblueprint.org/

# spordisemu

Spordisemu is an Android app for finding people to do sports together.

## Users collection [/users]

### List all users [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "username": "test",
                "password": "test"
            },
            {
                "id": 2,
                "username": "kalle123",
                "password": "vanaema"
            },
            {
                "id": 3,
                "username": "flamingo_9",
                "password": "linnud"
            },
            {
                "id": 4,
                "username": "bemmikummid",
                "password": "mul_on123"
            }
        ]

### Create a new user [POST]

+ Request (application/json)

        {
                "id": 5,
                "username": "uus",
                "password": "tuttuus"
        }

+ Response 201 (application/json)

    + Headers

            Location: /users/5

    + Body

            {
                "id": 5,
                "username": "uus",
                "password": "tuttuus"
            }


## One user collection [/users/?username]

### Show one user [GET]

+ Parameters
    + username (text) - username of a user

+ Response 200 (application/json)

        {
            "id": 1,
            "username": "test",
            "password": "test"
        }

## User profile collection [/profiles/?username]

### Show user's profile [GET]

+ Parameters
    + username (text) - username of a user
    
+ Response 200 (application/json)

        {
            "id": 1,
            "firstname": "Paul",
            "lastname": "Cabbage",
            "birthday": "29.02.1992",
            "gender": "m",
            "location": "Narnia",
            "pic": "http://trialx.org/wp-content/uploads/2012/04/animals/Cabbagehead-3.jpg"
        }
        
### Create new profile [POST]

+ Parameters
    + username (text) - username of a user
    
+ Request (application/json)

        {
            "id": 1,
            "firstname": "Paul",
            "lastname": "Cabbage",
            "birthday": "29.02.1992",
            "gender": "m",
            "location": "Hogwarts",
            "pic": "http://trialx.org/wp-content/uploads/2012/04/animals/Cabbagehead-3.jpg"
        }
        
+ Response 201 (application/json)

    + Headers

            Location: /profiles/1

    + Body

            {
                "id": 1,
                "firstname": "Paul",
                "lastname": "Cabbage",
                "birthday": "29.02.1992",
                "gender": "m",
                "location": "Hogwarts",
                "pic": "http://trialx.org/wp-content/uploads/2012/04/animals/Cabbagehead-3.jpg"
            }
        
## Ratings collection [/users/?username/ratings]

### Show all ratings of a user [GET]

+ Parameters
    + username (text) - username of a user
    
+ Response 200 (application/json)

        {
            "rating_id": 1,
            "user_id": 1,
            "commenter_id": 2,
            "rating": 1,
            "comment": "You're not a cabbage"
        }
        
### Create a new rating [POST]

+ Request (application/json)

        {
                "rating_id": 2,
                "user_id": 1,
                "commenter_id": 3,
                "rating": 5,
                "comment": "I like cabbages"
        }

+ Response 201 (application/json)

    + Headers

            Location: /users/?username/ratings/2

    + Body

            {
                "rating_id": 2,
                "user_id": 1,
                "commenter_id": 3,
                "rating": 5,
                "comment": "I like cabbages"
            }
            
## Practices collection [/practices]

### Show all practices [GET]

+ Response 200 (application/json)

        {
            "practice_id": 1,
            "type": "Quidditch",
            "timestamp": "2016-09-01 14:00:00",
            "location": "Hogwarts",
            "level": "novice",
            "user_id": 1
        }
        
### Create new practice [POST]
  
+ Request (application/json)

        {
            "practice_id": 2,
            "type": "Wizard chess",
            "timestamp": "2016-09-15 15:00:00",
            "location": "Hogwarts",
            "level": "expert",
            "user_id": 1
        }
        
+ Response 201 (application/json)

    + Headers

            Location: /practices/2

    + Body

            {
                "practice_id": 2,
                "type": "Wizard chess",
                "timestamp": "2016-09-15 15:00:00",
                "location": "Hogwarts",
                "level": "expert",
                "user_id": 1
            }
            
## Comments collection [/practices/?practice_id/comments]

### Show all practices [GET]

+ Parameters
    + practice_id (number) - id of a practice

+ Response 200 (application/json)

        {
            "comment_id": 1,
            "user_id": 2,
            "practice_id": 1,
            "comment": "Quidditch is not a real game"
        }
        
### Create new comment [POST]
  
+ Request (application/json)

        {
            "comment_id": 2,
            "user_id": 1,
            "practice_id": 1,
            "comment": "Yes it is (HP 4 life)"
        }
        
+ Response 201 (application/json)

    + Headers

            Location: /practices/1/comments/2

    + Body

            {
                "comment_id": 2,
                "user_id": 1,
                "practice_id": 1,
                "comment": "Yes it is (HP 4 life)"
            }
           
## Attend collection [/practices/?practice_id/attend]

### Show all attends [GET]

+ Parameters
    + practice_id (number) - id of a practice

+ Response 200 (application/json)

        {
            "attend_id": 1,
            "user_id": 2,
            "practice_id": 1
        }
        
### Create new attend [POST]
  
+ Request (application/json)

        {
            "attend_id": 2,
            "user_id": 3,
            "practice_id": 1
        }
        
+ Response 201 (application/json)

    + Headers

            Location: /practices/1/attend/2

    + Body

            {
                "attend_id": 2,
                "user_id": 3,
                "practice_id": 1
            }

        