FORMAT: 1A
HOST: http://spordisemu.apiblueprint.org/

# spordisemu

Spordisemu is an Android app for finding people to do sports together.

## Users collection [/users]

### List all users [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "firstname": "Test",
                "lastname": "Test",
                "username": "test",
                "gender": 0,
                "email": "test@mail.ee",
                "password": "testtest"
            },
            {
                "id": 2,
                "firstname": "Kalle", 
                "lastname": "Blomkvist", 
                "username": "kalle123",
                "gender": 1, 
                "email": "kalle123@mail.ee",
                "password": "vanaema"
            },
            {
                "id": 3,
                "firstname": "Peeter",
                "lastname": "Paan",
                "username": "flamingo9",
                "gender": 1,
                "email": "flamingo9@mail.ee",
                "password": "linnud"
            },
            {
                "id": 4,
                "firstname": "Bemm",
                "lastname": "Kumm",
                "username": "bemmikummid",
                "gender": 0,
                "email": "bemmikummid@mail.ee",
                "password": "mul_on123"
            }
        ]

### Create a new user [POST]

+ Request (application/json)

        {
                "firstname": "Uus",
                "lastname": "Uus",
                "username": "uus123",
                "gender": 1,
                "email": "uusTuus@tuus.ee",
                "password": "tuttuus"
        }

+ Response 201 (application/json)

    + Headers

            Location: /users/uus

    + Body

            {
                "id": 5,
                "firstname": Uus,
                "lastname": Uus
                "username": "uus123",
                "gender": 1
                "email": "uusTuus@tuus.ee"
                "password": "tuttuus"
            }


## One user collection [/users/{username}]

### Show one user [GET]

+ Parameters
    + username (text) - username of a user

+ Response 200 (application/json)

        {
            "id": 1,
            "firstname": "Test",
            "lastname": "Test",
            "username" : "test",
            "gender": 0,
            "email": "test@mail.ee",
            "password": "testtest"
        }

## User profile collection [/profiles/{user_id}]

### Show user's profile [GET]

+ Parameters
    + user_id (text) - id of a user
    
+ Response 200 (application/json)

        {
            "profile_id": 1,
            "user_id": 1,
            "location": "Narnia",
            "pic": "http://trialx.org/wp-content/uploads/2012/04/animals/Cabbagehead-3.jpg"
        }
        
### Create new profile [POST]

+ Parameters
    + user_id (text) - id of a user
    
+ Request (application/json)

        {
            "user_id": 5,
            "sports": "Korvpall",
            "level": "Kerge",
            "location": "Hogwarts",
            "pic": "http://trialx.org/wp-content/uploads/2012/04/animals/Cabbagehead-3.jpg"
        }
        
+ Response 201 (application/json)

    + Headers

            Location: /profiles/5

    + Body

            {
                "user_id": 5,
                "sports": "Korvpall",
                "level": "Kerge",
                "location": "Hogwarts",
                "pic": "http://trialx.org/wp-content/uploads/2012/04/animals/Cabbagehead-3.jpg"
            }

## Sports collection [/users/{user_id}/sports]

### Show all sports of a user [GET]

+ Parameters 
    + user_id (text) - id of a user
    
+ Response 200 (application/json)

        [
            {
                "sports_id" : 1, 
                "user_id" : 1,
                "sports" : "Jalgpall",
                "level" : "Kerge"
            },
            {
                "sports_id" : 2, 
                "user_id" : 1, 
                "sports" : "Sulgpall",
                "level" : "Keskmine"
            }
        ]
        
### Add sports to a user [POST]

+ Request (application/json)
    
        {
            "user_id" : 1,
            "sports" : "Korvpall", 
            "level" : "Raske"
        }

+ Response 201 (application/json)

    + Headers

            Location: /users/{user_id}/sports/2

    + Body

            {
                "sports_id" : 2,
                "user_id" : 1,
                "sports" : "Korvpall", 
                "level" : "Raske"
            }
        
## Ratings collection [/users/{user_id}/ratings]

### Show all ratings of a user [GET]

+ Parameters
    + user_id (text) - id of a user
    
+ Response 200 (application/json)

        {
            "rating_id": 1,
            "user_id": 1,
            "commenter_id": 2,
            "rating": 1,
            "comment": "You're not a cabbage"
        }
        
### Create a new rating [POST]

+ Request (application/json)

        {
                "rating_id": 2,
                "user_id": 1,
                "commenter_id": 3,
                "rating": 5,
                "comment": "I like cabbages"
        }

+ Response 201 (application/json)

    + Headers

            Location: /users/{user_id}/ratings/2

    + Body

            {
                "rating_id": 2,
                "user_id": 1,
                "commenter_id": 3,
                "rating": 5,
                "comment": "I like cabbages"
            }
            
## Practices collection [/practices]

### Show all practices [GET]

+ Response 200 (application/json)

        [
            {
                "practice_id": 1,
                "type": "Jalgpall",
                "timestamp": "2016-09-01 14:00:00",
                "location": "Tamme Staadion",
                "level": "Raske",
                "user_id": 1
            },
            {
                "practice_id": 2,
                "type": "Korvpall",
                "timestamp": "2016-10-01 14:00:00",
                "location": "Väljak",
                "level": "Kerge",
                "user_id": 3
            },
            {
                "practice_id": 3,
                "type": "Sulgpall",
                "timestamp": "2016-10-08 14:00:00",
                "location": "Minu hoovis",
                "level": "Algaja",
                "user_id": 4
            },
            {
                "practice_id": 4,
                "type": "Jalgpall",
                "timestamp": "2016-10-11 14:00:00",
                "location": "Vaatab veel",
                "level": "Ekspert",
                "user_id": 1
            },
            {
                "practice_id": 5,
                "type": "Mädamuna",
                "timestamp": "2016-11-01 14:00:00",
                "location": "Põllu peal",
                "level": "Kerge",
                "user_id": 1
            }
        ]
        
### Create new practice [POST]
  
+ Request (application/json)

        {
            "type": "Wizard chess",
            "timestamp": "2016-09-15 15:00:00",
            "location": "Hogwarts",
            "level": "Raske",
            "user_id": 1
        }
        
+ Response 201 (application/json)

    + Headers

            Location: /practices/6

    + Body

            {
                "practice_id": 6,
                "type": "Wizard chess",
                "timestamp": "2016-09-15 15:00:00",
                "location": "Hogwarts",
                "level": "Raske",
                "user_id": 1
            }
            
## One practice collection [/practices/{practice_id}]

### Show one practice [GET]

+ Parameters
    + practice_id (number) - id of a practice

+ Response 200 (application/json)

        {
            "practice_id": 1,
            "type": "Jalgpall",
            "timestamp": "2016-09-01 14:00:00",
            "location": "Tamme Staadion",
            "level": "Raske",
            "user_id": 1
        }
            
## Comments collection [/practices/{practice_id}/comments]

### Show all comments [GET]

+ Parameters
    + practice_id (number) - id of a practice

+ Response 200 (application/json)

        {
            "comment_id": 1,
            "user_id": 2,
            "practice_id": 1,
            "comment": "See mäng on nõme"
        },
        {
            "comment_id": 2,
            "user_id": 3,
            "practice_id": 1,
            "comment": "Mulle ka ei meeldi see mäng"
        },
        {
            "comment_id": 3,
            "user_id": 1,
            "practice_id": 2,
            "comment": "Ma ei saa kahjuks tulla :("
        }
        
### Create new comment [POST]
  
+ Request (application/json)

        {
            "user_id": 1,
            "practice_id": 1,
            "comment": "Mulle küll meeldib"
        }
        
+ Response 201 (application/json)

    + Headers

            Location: /practices/1/comments/4

    + Body

            {
                "comment_id": 4,
                "user_id": 1,
                "practice_id": 1,
                "comment": "Mulle küll meeldib"
            }
           
## Attend collection [/practices/{practice_id}/attends]

### Show all attends of a practice [GET]

+ Parameters
    + practice_id (number) - id of a practice

+ Response 200 (application/json)

        {
            "attend_id": 1,
            "user_id": 2,
            "practice_id": 1
        },
        {
            "attend_id": 2,
            "user_id": 3,
            "practice_id": 1
        }
        
### Create new attend [POST]
  
+ Request (application/json)

        {
            "user_id": 3,
            "practice_id": 2
        }
        
+ Response 201 (application/json)

    + Headers

            Location: /practices/2/attend/2

    + Body

            {
                "attend_id": 2,
                "user_id": 3,
                "practice_id": 2
            }

## Practice additional information collection [/practices/{practice_id}/additional]

### Show additional information of a practice [GET]

+ Parameters
    + practice_id (number) - id of a practice
    
+ Response 200 (application/json)

        {
            "practice_id": 1,
            "min": 3,
            "max": 15,
            "gender": 1
        }

### Create new additional information of a practice [POST]

+ Request (application/json)
        
        {
            "practice_id": 2,
            "min": 1,
            "max": 10,
            "gender": 0
        }

+ Response 201 (application/json)

    + Headers

            Location: /practices/2/additional

    + Body

            {
                "practice_id": 2,
                "min": 1,
                "max": 10,
                "gender": 0
            }